name: better_imports
description: A CLI tool to automatically sort and organize Dart imports in your project files, supporting custom rules, configs, and formatting options.
version: 1.4.1
repository: https://github.com/oppahansi/better_imports

executables:
  better_imports: better_imports

environment:
  sdk: '>=3.5.0 <4.0.0' 

dependencies:
  analyzer: ^7.3.0
  args: ^2.5.0
  dart_style: ^3.1.0-wip
  intl: ^0.20.2
  logging: ^1.2.0
  tint: ^2.0.1
  yaml: ^3.1.2
  pub_semver: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8

# Better Imports default config
# Default config is overwritten when settings are passed in as arguments in the cli
better_imports:
  # If set overwrites the project name
  # Used for sorting project imports
  project_name:

  # Absolute path to an external configuration
  # If set, rest in this section will be ignored
  cfg_path:

  # Flag to include subfolders
  recursive: true

  # Flag to add comments above import sections
  comments: true

  # Flag to disable results output in console
  silent: false

  # Flag to use relative imports in the project
  relative: false

  # Flag to use to log everything happening to console
  trace: false

  # Flag to use to run a dry run without changing files
  dry_run: false

 # Flag to use the dart formatter after sorting imports
  dart_fmt: true

  # Folder names used for collecting dart files
  folders:
    - lib
    - bin
    - res
    - example
    - test
    - tests
    - integration_test
    - integration_tests
    - test_driver

  # File names which should be sorted
  files:

  # File names which should be excluded
  ignore_files:

  # RegEx pattern for files which should be collected
  files_like:

  # RegEx pattern for files which should be excluded
  ignore_files_like:
    - .*generated_plugin_registrant\.dart
    - .*\.g\.dart
    - .*\.gr\.dart
    - .*\.freezed\.dart