name: better_imports
description: A better imports sorter for your .dart files.
version: 1.0.0
repository: https://github.com/oppahansi/better_imports

environment:
  sdk: '>=3.2.2'

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  tint: ^2.0.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

# Better Imports default config
# Default config is overwritten when settings are passed in as arguments in the cli
better_imports:
  # If set overwrites the project name
  # Used for sorting project imports
  project_name:

  # Absolute path to an external configuration
  # If set, rest in this section will be ignored
  cfg_path:

  # Flag to include subfolders
  recursive: true

  # Flag to add comments above import sections
  comments: true

  # Flag to disable results output in console
  silent: false

  # Flag to use relative imports in the project
  relative: false

  # Folder names used for collecting dart files
  folders:
    - lib
    - bin
    - example
    - test
    - tests
    - integration_test
    - integration_tests
    - test_driver

  # Files which should be sorted
  files:

  # RegEx for files which should be collected
  files_like:

  # RegEx for files which should be excluded
  ignore_files_like:
    - .*generated_plugin_registrant\.dart
    - .*\.g\.dart
    - .*\.gr\.dart
    - .*\.freezed\.dart